---
title: "P622-3 10X fixed data: Cell count numbers loading vs captured"
output: html_document
author: Naresh Doni Jayavelu
---

&nbsp;

&nbsp;

&nbsp;


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

&nbsp;

&nbsp;

&nbsp;

## Load all necessary libraries, although I do not like to.

```{r loadLibraries, message=FALSE, warning=FALSE, echo=FALSE}
library(Seurat)
library(stringr)
library(ggpubr)
library(gridExtra)
library(car)
library(lme4)
# library(garnett)
library(ggrepel)
library(ggrastr)
library(dplyr)
library(tidyverse)
library(presto)
library(kableExtra)
library(patchwork)
library(ggbeeswarm)
# library(rlang)
library(ggrastr)
# library(BPCells)
library(igraph)
library(ggraph)
library(RColorBrewer)
library(scales)
library(ComplexUpset)
library(gt)

options(stringsAsFactors = FALSE)
set.seed(100)

Csparse_validate = "CsparseMatrix_validate"

```

&nbsp;

&nbsp;

&nbsp;

### Set up the directories
```{r set_up_directories, cache = TRUE}
# baseDir <- "/mnt/bioinformatics/workspace/ndonijayavelu/P608_5_analysis_server"
# baseDir_isilon <- "/nfs/bioinformatics/workspace/ndonijayavelu/P608_5_analysis_server"
baseDir <- "/nfs/pure_bioinformatics/workspace/ndonijayavelu/P622_analysis_pure_server"
# annoExtDir <- "/mnt/bioinformatics/workspace/ndonijayavelu/Annotation_files"
outDir <- file.path(baseDir, "output")
dataDir <- file.path(baseDir, "data")
processedDataDir <- file.path(baseDir, "processed_data")
annoDir <- file.path(baseDir, "annotation")
# tabDir <- file.path(outDir, "scanpy_related", "Tables")
# scanpyDir <- file.path(outDir, "scanpy_related", "without_T176")
# scanpyDir_isilon <- file.path(baseDir_isilon, "output", "scanpy_related", "without_T176")
# degDir <- file.path(outDir, "scanpy_related", "without_T176", "DEGs_list")
# figDir <- file.path(outDir, "scanpy_related", "without_T176", "DEGs_list", "Figures")
# degDir <- file.path(baseDir, "code/without_T176/PseudoBulk_analysis/4_conditions")
# enrichRDir <- file.path(baseDir, "enrichR_database")
# enrichDir <- file.path(baseDir, "code/without_T176/PseudoBulk_DEGs_enrichments")
# figDir <- file.path(baseDir, "code/without_T176/Figs_AAAAI_Feb2026/T2_signature_vs_cellComp")

```


### Define color codes
```{r set_up_directories, cache = TRUE}

col_sel_cell <- c("Basal" = "#DDCBA4FF", "MitoticBasal" = "#D99E4CFF", 
             "SupraBasal" = "#BE3428FF", "Secretory" = "#95C65CFF", 
             "Club" = "#088BBEFF", "Goblet" = "#F28A8AFF", 
             "MucousSecretory" = "#0E7175FF","MucousCiliated" = "#94D0FFFF", 
             "Deuterosomal" = "#FFB900FF", "Ciliated" = "#8795E8FF", 
             "RareCells" = "#C774E8FF")


col_sel_donor <- c(Healthy = "darkgrey", "Non-T2" = "#5773CCFF", "T2" = "#FFB900FF")

col_sel_condition <- c("Uninfected" = "#66C2A5", "RV16" = "#FC8D62", "IL-13" = "#8DA0CB", "IL-13_RV16" = "#E78AC3")

cell_type_levels = c("Basal", "MitoticBasal", "SupraBasal", "Secretory", 
                       "Club", "Goblet", "MucousSecretory", "MucousCiliated", 
                       "Deuterosomal", "Ciliated", "RareCells")
condition_levels <- c("Uninfected", "RV16", "IL-13", "IL-13_RV16")

```


### Read cell count metadata

```{r Read the marker genes list}

CR_ED_qc_metrics <- read_csv(file = file.path(outDir, "CR_ED_qc_metrics_with_sample_metadata.csv"))

CR_ED_qc_metrics_select <- CR_ED_qc_metrics %>%
  select(orig.ident, pre_hyb_cell_count_total, cell_number_input_in_to_hyb, num_cells_beforeQC_CR, num_cells_beforeQC_ED)


library(ggplot2)
library(tidyr)
library(dplyr)
library(ggpubr)
library(ggrepel)

### Pre-Hybridization Cell Count vs Recovered Cells
# Reshape to long format
plot_data <- CR_ED_qc_metrics_select %>%
  select(orig.ident, pre_hyb_cell_count_total, num_cells_beforeQC_CR, num_cells_beforeQC_ED) %>%
  pivot_longer(
    cols      = c(num_cells_beforeQC_CR, num_cells_beforeQC_ED),
    names_to  = "method",
    values_to = "num_cells"
  ) %>%
  mutate(method = recode(method,
                         "num_cells_beforeQC_CR" = "CellRanger",
                         "num_cells_beforeQC_ED" = "EmptyDrops"))

pp <- ggplot(plot_data,
       aes(x     = num_cells,
           y     = pre_hyb_cell_count_total,
           color = method,
           fill  = method)) +
  geom_point(size  = 3,
             alpha = 0.8) +
  geom_smooth(method    = "lm",
              se        = TRUE,
              alpha     = 0.15,
              linewidth = 1) +
  # geom_text_repel(aes(label = orig.ident),
  #                 size         = 3,
  #                 max.overlaps = 20,
  #                 show.legend  = FALSE) +
  stat_cor(aes(label = paste(..rr.label.., ..p.label.., sep = "~`,`~")),
           show.legend = FALSE,
           size        = 3.5) +
  scale_color_manual(values = c("CellRanger" = "#4D4D4DFF",
                                "EmptyDrops" = "#2CA02CFF")) +
  scale_fill_manual(values  = c("CellRanger" = "#4D4D4DFF",
                                "EmptyDrops" = "#2CA02CFF")) +
  scale_x_continuous(labels = scales::comma) +
  scale_y_continuous(labels = scales::comma) +
  labs(title    = "Pre-Hybridization Cell Count vs Recovered Cells",
       subtitle = "CellRanger vs EmptyDrops",
       y        = "Pre-Hyb Cell Count (Total)",
       x        = "Number of Cells Before QC",
       color    = "Method",
       fill     = "Method") +
  theme_bw() +
  theme(
    plot.title       = element_text(hjust = 0.5, face = "bold", size = 14),
    plot.subtitle    = element_text(hjust = 0.5, size = 11),
    axis.text        = element_text(size = 10),
    axis.title       = element_text(face = "bold", size = 11),
    legend.position  = "right",
    legend.title     = element_text(face = "bold"),
    panel.grid.minor = element_blank()
  )

# ### Input Hybridization Cell Count vs Recovered Cells
# Reshape to long format
plot_data <- CR_ED_qc_metrics_select %>%
  select(orig.ident, cell_number_input_in_to_hyb, num_cells_beforeQC_CR, num_cells_beforeQC_ED) %>%
  pivot_longer(
    cols      = c(num_cells_beforeQC_CR, num_cells_beforeQC_ED),
    names_to  = "method",
    values_to = "num_cells"
  ) %>%
  mutate(method = recode(method,
                         "num_cells_beforeQC_CR" = "CellRanger",
                         "num_cells_beforeQC_ED" = "EmptyDrops"))

pp <- ggplot(plot_data,
       aes(x     = num_cells,
           y     = cell_number_input_in_to_hyb,
           color = method,
           fill  = method)) +
  geom_point(size  = 3,
             alpha = 0.8) +
  geom_smooth(method    = "lm",
              se        = TRUE,
              alpha     = 0.15,
              linewidth = 1) +
  # geom_text_repel(aes(label = orig.ident),
  #                 size         = 3,
  #                 max.overlaps = 20,
  #                 show.legend  = FALSE) +
  stat_cor(aes(label = paste(..rr.label.., ..p.label.., sep = "~`,`~")),
           show.legend = FALSE,
           size        = 3.5) +
  scale_color_manual(values = c("CellRanger" = "#4D4D4DFF",
                                "EmptyDrops" = "#2CA02CFF")) +
  scale_fill_manual(values  = c("CellRanger" = "#4D4D4DFF",
                                "EmptyDrops" = "#2CA02CFF")) +
  scale_x_continuous(labels = scales::comma) +
  scale_y_continuous(labels = scales::comma) +
  labs(title    = "Input Hybridization Cell Count vs Recovered Cells",
       subtitle = "CellRanger vs EmptyDrops",
       y        = "Input Hybridization Cell Count",
       x        = "Number of Cells Before QC",
       color    = "Method",
       fill     = "Method") +
  theme_bw() +
  theme(
    plot.title       = element_text(hjust = 0.5, face = "bold", size = 14),
    plot.subtitle    = element_text(hjust = 0.5, size = 11),
    axis.text        = element_text(size = 10),
    axis.title       = element_text(face = "bold", size = 11),
    legend.position  = "right",
    legend.title     = element_text(face = "bold"),
    panel.grid.minor = element_blank()
  )


# ggsave(file.path(outDir, "scatter_preHyb_vs_cellRecovery_CR_ED.png"),
#        width  = 10,
#        height = 7,
#        dpi    = 150)


### gt table
library(gt)
library(dplyr)

tb <- CR_ED_qc_metrics_select %>%
  arrange(desc(num_cells_beforeQC_ED)) %>%
  mutate(
    ED_gain     = num_cells_beforeQC_ED - num_cells_beforeQC_CR,
    ED_gain_pct = round(ED_gain / num_cells_beforeQC_CR * 100, 2)
  ) %>%
  gt() %>%
  tab_header(
    title    = md("**Cell Recovery Summary: CellRanger vs EmptyDrops**"),
    subtitle = md("Rows ordered by EmptyDrops cell recovery (descending)")
  ) %>%
  cols_label(
    orig.ident                  = md("**Sample**"),
    pre_hyb_cell_count_total    = md("**Pre-Hyb Count**"),
    cell_number_input_in_to_hyb = md("**Input to Hyb**"),
    num_cells_beforeQC_CR       = md("**CR Cells**"),
    num_cells_beforeQC_ED       = md("**ED Cells**"),
    ED_gain                     = md("**ED Gain**"),
    ED_gain_pct                 = md("**% Gain**")
  ) %>%
  tab_spanner(
    label   = md("**Input**"),
    columns = c(pre_hyb_cell_count_total, cell_number_input_in_to_hyb)
  ) %>%
  tab_spanner(
    label   = md("**Cell Recovery**"),
    columns = c(num_cells_beforeQC_CR, num_cells_beforeQC_ED, ED_gain, ED_gain_pct)
  ) %>%
  data_color(
    columns = num_cells_beforeQC_ED,
    palette = "Blues"
  ) %>%
  data_color(
    columns = num_cells_beforeQC_CR,
    palette = "Greys"
  ) %>%
  data_color(
    columns = ED_gain_pct,
    palette = c("white", "#2CA02CFF")
  ) %>%
  # Highlight negative gains (ED recovered fewer cells than CR)
  tab_style(
    style     = cell_fill(color = "#D6272833"),
    locations = cells_body(rows = ED_gain < 0)
  ) %>%
  tab_style(
    style     = cell_text(weight = "bold"),
    locations = cells_body(columns = orig.ident)
  ) %>%
  fmt_number(
    columns  = c(pre_hyb_cell_count_total, cell_number_input_in_to_hyb,
                 num_cells_beforeQC_CR, num_cells_beforeQC_ED, ED_gain),
    decimals = 0,
    use_seps = TRUE
  ) %>%
  fmt_number(
    columns  = ED_gain_pct,
    decimals = 2
  ) %>%
  grand_summary_rows(
    columns = c(pre_hyb_cell_count_total, cell_number_input_in_to_hyb,
                num_cells_beforeQC_CR, num_cells_beforeQC_ED, ED_gain),
    fns     = list(Total ~ sum(.)),
    fmt     = ~ fmt_number(., decimals = 0, use_seps = TRUE)
  ) %>%
  tab_footnote(
    footnote  = "ED Gain = EmptyDrops cells minus CellRanger cells. Rows in red = ED recovered fewer cells than CR.",
    locations = cells_column_labels(columns = ED_gain)
  ) %>%
  tab_options(
    table.font.size                 = 13,
    heading.title.font.size         = 16,
    heading.subtitle.font.size      = 12,
    column_labels.font.weight       = "bold",
    table.border.top.color          = "black",
    table.border.bottom.color       = "black",
    row.striping.include_table_body = TRUE,
    row.striping.background_color   = "#F9F9F9"
  )

library(gtExtras)
gtsave(tb, filename = file.path(outDir, "Cellcounts_loaded_vs_captuted_per_sample_CR_vs_ED.html"))

```




### Read cell count metadata

```{r Read the marker genes list}

# CR
load(file = file.path(processedDataDir, "cell_metadata_CR_temp_260226.rda")) # cell_metadata_CR

# ED
load(file = file.path(processedDataDir, "cell_metadata_ED_temp_260226.rda")) # cell_metadata_ED


```

